id: 8569a499-83ef-4a94-bc63-01bdd45023e5
type: database
provider: sqlserver
name: Database
description: Example of database with SQL Server as provider
annotations:
- namespace: c4modeler
  name: position
  value:
    container:
      x: 139.5
      y: 376
